# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_boba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesDrugged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesDrugged', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bobaplaces',
            name='user',
        ),
        migrations.AddField(
            model_name='bobaplaces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bobaplaces',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timesdrugged',
            name='bobaplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_boba.BobaPlaces'),
        ),
        migrations.AddField(
            model_name='timesdrugged',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_boba.Users'),
        ),
    ]
