# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_boba', '0002_auto_20170727_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('druggie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_boba.BobaPlaces')),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='track_boba.Users')),
            ],
        ),
    ]
