# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_boba', '0004_auto_20170727_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='track_boba.Users'),
        ),
    ]
